### PR TITLE
fix #120 by removing Puerto Rico from world.yml

### LINKED ISSUE #120: Puerto Rico is both a region and a country.
I think it should only be an outlying area. Are there any particular reason why it's both?

### PR DESCRIPTION
**Pull request by tim-evans**
Fairly self explanatory.

### CODE REVIEW

**Comment by fpcyan** [comment]
@jim any chance to revert this? ISO 3166-2 includes Puerto Rico as a country (and as a subdivision of the USA, see: https://www.iso.org/obp/ui/#iso:code:3166:PR). Both PR as a "state of the US" and PR as a country are commonly used.

**Comment by j15e** [comment]
I think it Puerto Rico should be enable by default because it is in the ISO database and it is probably useful in many cases (ex. shipping address I think Puerto Rico is listed as a country by most shipping companies). 

And let developers disable it if they do no want to have it in their specific countries list.

**Comment by fpcyan** [comment]
@j15e Sorry if I'm misunderstanding. Are you saying that it *is* enabled by default? Or are you saying that it *should be* enabled by default, and developers should disable it if they don't want it?

**Comment by j15e** [comment]
>  it should be enabled by default, and developers should disable it if they don't want it

I agree on what you said.

**Comment by fpcyan** [comment]
I thought so, but I wanted to just be sure! The current version of Carmen already allows developers to remove anything they do not want. How do we feel about reverting this?

**Pull request closed without merging**
