### PR TITLE
Add country search by numeric code

### PR DESCRIPTION
**Pull request by Envek**
This pull request extends #125 allowing not only access country's numeric code value but also allows to search countries by numeric code.

### CODE REVIEW

**Comment by ecbypi** [comment]
@CDainMiller Thoughts on this PR?   I had some thoughts on this outlined in #170.

**Comment by CDainMiller** [comment]
Thanks @ecbypi - I'll follow up in #170

**Comment by CDainMiller** [comment]
@jim What should we do here? Still thinking this looks good for a release? I'm not sure, but maybe this is something we want to merge into a version-2.0 branch instead of master?

**Comment by Envek** [comment]
Wow, this PR is already two years old and still mergeable! @jim, what do you think about it now?

**Comment by jim** [comment]
I think I intended to merge this a while ago. Sorry for the delay, @Envek. It's a small change to the existing API, and as several uses will find this useful, that's a good enough reason for me.

**Pull request merged**
